name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev libc6-dev

    - name: Install Android SDK & Build-Tools
      run: |
        sudo mkdir -p /usr/lib/android-sdk
        sudo chown $USER:$USER /usr/lib/android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
        unzip cmdtools.zip
        sudo mkdir -p /usr/lib/android-sdk/cmdline-tools/latest
        sudo mv cmdline-tools/* /usr/lib/android-sdk/cmdline-tools/latest
        yes | /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;36.0.1"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install buildozer + deps
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install buildozer cython virtualenv
        pip install "Cython<3.0.10"

    - name: Build APK
      run: |
        source env/bin/activate
        export ANDROIDSDK=/usr/lib/android-sdk
        export ANDROIDNDK=/usr/lib/android-sdk/ndk-bundle
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BoodupPark-APK
        path: bin/*.apk
